export const COLUMNS_HARDCODE = {
  FIRST: 10,
  SECOND: 11,
  THIRD: 11,
};

export const galleryPaintingsData = [
  {
    name: "Desert Flower",
    technique: "Oil, acrylic, glue and mirror from recycling on canvas",
    size: "120 x 100 cm",
    year: "2020",
    price: "FOR SALE",
    file: "00-mirror",
  },
  {
    name: "Mirror Selfie",
    technique: "Oil, acrylic, glue and mirror from recycling on canvas",
    size: "120 x 120 cm",
    price: "FOR SALE",
    year: "2020",
    file: "0-mirror",
  },
  {
    name: "Magdalena",
    technique: "acrylic on canvas",
    size: "120 x 100 cm",
    year: "2020",
    price: "SOLD",
    file: "1-MAGDALENA",
  },
  {
    name: "Paaaa",
    technique: "mixed media on linen",
    size: "100 x 100 cm",
    year: "2019",
    price: "SOLD",
    file: "2-PAAAA",
  },
  {
    name: "Background Elf",
    technique: "acrylic and oil on canvas",
    size: "120 x 120 cm",
    year: "2019",
    price: "FOR SALE",
    file: "3-Background-elf",
  },
  {
    name: "Hał macz ys de fysz",
    technique: "acrylic on canvas / UV",
    size: "120 x 100 cm",
    year: "2019",
    price: "FOR SALE",
    file: "4-Hae-macz-ys-de-fysz",
    uv: true,
  },
  {
    name: "Turquoise warrior",
    technique: "mixed media on canvas / UV",
    size: "100 x 100 cm",
    year: "2019",
    price: "SOLD",
    file: "5-Turquoise-warrior",
    uv: true,
  },
  {
    name: "COUCOU CHLOE",
    technique: "mixed media on canvas / mirror",
    size: "60 x 80 cm",
    year: "2019",
    file: "6-COUCOU-CHLOE",
  },
  {
    name: "ultraMARYna",
    technique: "acrylic on canvas",
    size: "100 x 100 cm",
    year: "2019",
    price: "FOR SALE",
    file: "7-ultraMARYna",
  },
  {
    name: "SNAiL",
    technique: "acrylic on canvas",
    size: "100 x 120 cm",
    year: "2019",
    price: "FOR SALE",
    file: "8-SNAIL",
    detail: true,
  },

  {
    name: "SOAP",
    technique: "acrylic on canvas",
    size: "100 x 120 cm",
    year: "2019",
    file: "9-SOAP",
  },
  {
    name: "zielONA",
    technique: "acrylic on linen",
    size: "100 x 100 cm",
    year: "2019",
    price: "FOR SALE",
    file: "10-zielONA",
  },
  {
    name: "GENDER",
    technique: "acrylic on canvas / UV",
    size: "100 x 100 cm",
    year: "2019",
    price: "SOLD",
    file: "11-GENDER",
    uv: true,
  },

  {
    name: "Żemień",
    technique: "mixed media on canvas / UV",
    size: "120 x 100 cm",
    year: "2019",
    price: "SOLD",
    file: "12-zem",
    uv: true,
  },

  {
    name: "Classic lollipop",
    technique: "acrylic on canvas / UV",
    size: "120x100 cm",
    year: "2019",
    price: "FOR SALE",
    file: "13-classic-lollipop",
  },

  {
    name: "Insigthful",
    technique: "acrylic on canvas / UV",
    size: "120x120cm",
    year: "2018",
    file: "14-Insigthful",
    uv: true,
  },
  {
    name: "Metallic nymph",
    technique: "acrylic on canvas / UV",
    size: "120 x 120 cm",
    year: "2018",
    file: "15-metallic-nymph",
  },
  {
    name: "Nefertiti",
    technique: "mixed media on canvas / mirror",
    size: "100 x 120 cm",
    year: "2020",
    file: "16-Nefertiti",
  },
  {
    name: "Boska Bożenka",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "17-bozenka",
    uv: true,
  },
  {
    name: "ELEONORA",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2018",
    file: "18-eleonora",
    uv: true,
  },
  {
    name: "Dama z Łysiczką",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2018",
    file: "19-dama",
    uv: true,
  },
  {
    name: "Burczybear",
    technique: "acrylic on canvas",
    size: "120 x 120 cm",
    year: "2018",
    file: "20-pham",
  },
  {
    name: "Stachursky",
    technique: "acrylic on canvas / UV",
    size: "100 x 100 cm",
    year: "2019",
    file: "21-stachursky",
    uv: true,
  },
  {
    name: "Karolina Dobkowska",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2019",
    file: "22-karolinka",
  },
  {
    name: "Krzysztof Krawczyk",
    technique: "acrylic on canvas",
    size: "80 x 80 cm",
    year: "2018",
    file: "23-krzysztof-krawczyk",
  },
  {
    name: "Frida",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2018",
    file: "24-frida",
    uv: true,
  },
  {
    name: "Pansua",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "25-pansia",
    uv: true,
  },
  {
    name: "Sita Gold",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "sita-gold",
    uv: true,
  },
  {
    name: "Sita",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "sita",
    uv: true,
  },
  {
    name: "Beata",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2018",
    file: "beata",
    uv: true,
  },
  {
    name: "Ming",
    technique: "acrylic on canvas /  UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "mingx",
  },
  {
    name: "BVLD",
    technique: "acrylic on canvas / UV",
    size: "80 x 80 cm",
    year: "2017",
    file: "lysa",
  },
];

const getPairedGallery = () => {
  const pairData = {};
  galleryPaintingsData.forEach((item) => {
    pairData[item.name] = item;
  });
  return pairData;
};

export const pairedGallery = getPairedGallery();
